name: openconnect
services:
    openconnect:
        container_name: openconnect
        image: openconnect
        build: ./openconnect
        ports:
            - 6666:6666 # Socks port
        stdin_open: true
        tty: true
        privileged: true
        environment:
            - OPENSSL_CONF=/cert/openssl_conf.cnf # Fix old protocols
        
        # Create a volume with your certificate if you VPN requires it

        #volumes:
        #    - <cert_path>:<cert_path>
